name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.7'  # Укажите нужную версию PHP
          extensions: mbstring, sqlite3, xml

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Create .env file
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/home/runner/work/linkshort1/linkshort1/database/database.sqlite" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force  # Выполняем миграции

      - name: Run tests
        run: php artisan test  # Запустите ваши тесты, если они есть


      - name: Install PHP extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y php8.2-common php8.2-fileinfo

      - name: Update Composer dependencies
        run: composer update


      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Build and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@194.87.215.192 "cd /www/wwwroot/lara1.pupupu.my && git pull origin main && composer install && php artisan migrate"
